### Projet 3 : Synthetisé des données médicales avec la méthode avatar (présenté dans cette [article](https://www.nature.com/articles/s41746-023-00771-5))

**Problématique :** Rocher et al. ont montré que 99,98 % des personnes pouvaient être réidentifiées dans n’importe quel ensemble de données pseudonymisées à l’aide de 15 attributs démographiques. Depuis 2018, la mise en œuvre du Règlement général sur la protection des données (RGPD) en Europe a considérablement modifié le cadre réglementaire de la circulation et de l’utilisation des données personnelles, en favorisant notamment une utilisation plus systématique des techniques d’anonymisation. Pour répondre à ces exigences légales et de confidentialité, les techniques d’anonymisation constituent des solutions pertinentes pour la protection des données. Meme avec une anonymisation il y a toujours un risque de réidentification . 

**La solution :** Remplacer les données réelles par des données synthétiques (méthode Avatar), qui génèrent de nouveaux individus artificiels préservant les propriétés statistiques, tout en éliminant le risque de réidentification des personnes réelles.

**Explications :**
> Chaque avatar est basé sur un patient réel , mais il n'est PAS une copie de ce patient
> Le patient sert de point de départ mais ne contribue pas directement à son avatar . 

- Ex : Pour un patient A :
    - on regarde ses voisins
    - on génère un point autour ( avatar proches des vrais )
MAIS on n’utilise PAS directement A
 
> Le modèle ne génère PAS globalement il travaille dans un petit voisinage local (groupe de patients similaires) , parceque les relations statistiques sont locales
- Ex : patients similaires → mêmes patterns médicaux
- Donc on genere autour du patient 

> Difference avec d'autre modeles GAN/CTGAN :
- apprend une distribution globale
- peut générer n’importe où

> Certains approches disent  "plus les données synthétiques sont loin des vraies → plus c’est sécurisé", donc essaie de  maximiser la distance (synthetic vs real) . Ce qui creer des distribution fausses , corrélation cassé et des modeles ML inutile. La méthodes Avatars dit qu on reste proches des données rééls sans copier mais melanger , donc les donnée :
- restes réalistes 
- mais ne sont pas idéntiques

> Pourquoi faible risque de réidentification ? 
- parcque l’avatar est une combinaison de plusieurs individus
- donc impossible de dire "cet avatar = ce patient"

> Utilité statistiques : le papier dit  même interprétation que les données réelles , c est a dire : 
- distributions proches (reste dans les zones existantes)
- corrélations conservées (mélange des profils similaires)
- modèles ML donnent mêmes résultats ( garde les relations )

AVATAR ne crée rien de nouveau, il recombine intelligemment ce qui existe déjà (combinaison de voisins similaires)

> Pourquoi la projection PCA est au coeur de la méthode : 
- dans les données beaucoup de variables , le calcul de distances deviennent dificille, KNN ne marche pas bien .
- la solution est de projeter les données dans un espace réduit , on garde l essentiel de l information et les distances sont faciles a calculer 
- C est important car les voisins dépendent de la distance
- mauvaise projection = mauvais voisins = mauvais dataset

> L influence de k selon l article : 
- si cas petit : k = 5
    - mélange de 5 patients très proches
    - très réaliste
    - risque de confidentialité 
    - avatar moins diversifié 

- si cas grand : k=50
    - mélange large
    - plus flou
    - securisé 
    - avatar plus diversifié

> k influence confidentialité ET qualité . 

> L auteur propose d adapter k selon la densité :
- zone dense → petit k
- zone rare → grand k

> AVATAR permet de générer autant de données que l on souhaite , chaque génération est différente (processus àleatoires)

### Importation

In [1]:
import polars as pl
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors
from scipy.stats import wasserstein_distance
from sklearn.metrics import pairwise_distances
from sklearn.preprocessing import FunctionTransformer , StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.feature_selection import VarianceThreshold
import itertools
from sklearn.feature_selection import VarianceThreshold

import math

In [2]:
pl.Config.set_tbl_cols(-1) # afficher toute les colonnes 
pl.Config.set_tbl_rows(-1) # afficher toute les lignes

polars.config.Config

In [3]:
data="../../Data/trainDataDC2.csv.gz"
df=pl.read_csv(data)
df.shape

(14575, 21)

In [4]:
df.schema

Schema([('patid', Int64),
        ('index_age', String),
        ('previous_asthma_drugs', String),
        ('total_pre_index_cannisters_365', String),
        ('post_index_exacerbations365', Int64),
        ('pneumonia', String),
        ('sinusitis', String),
        ('acute_bronchitis', String),
        ('acute_laryngitis', String),
        ('upper_respiratory_infection', String),
        ('gerd', String),
        ('rhinitis', String),
        ('adherence', String),
        ('total_pre_index_charge', String),
        ('pre_asthma_days', String),
        ('pre_asthma_charge', String),
        ('pre_asthma_pharma_charge', String),
        ('drug_s', String),
        ('female', String),
        ('log_charges', String),
        ('log_asthma_charge', String)])

### Preprocessing

In [5]:
df.glimpse()
# affiche :
#le nombre de lignes
# le nombre de colonnes
# le nom et le type de chaque variable
# les valeurs exemples de chaque colonne

Rows: 14575
Columns: 21
$ patid                          <i64> 1073754155, 1073799394, 1073854918, 1073898249, 1073913003, 1073928980, 1074030062, 1074078078, 1074166886, 1074184402
$ index_age                      <str> '14', 'NA', '62', 'NA', '40', '64', '37', '62', '18', 'NA'
$ previous_asthma_drugs          <str> '1', '1', '1', '1', '1', '1', 'NA', '1', '1', '1'
$ total_pre_index_cannisters_365 <str> '1', '2', 'NA', '2', '1', '1', '0', '1', '1', '2'
$ post_index_exacerbations365    <i64> 0, 2, 0, 0, 0, 0, 0, 0, 0, 0
$ pneumonia                      <str> '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'
$ sinusitis                      <str> '0', '1', '0', '0', '1', '0', '0', '0', 'NA', '0'
$ acute_bronchitis               <str> '1', '1', 'NA', '1', '0', '1', '1', '0', '0', '1'
$ acute_laryngitis               <str> '0', '0', '0', '0', '1', '0', '0', '0', '0', '0'
$ upper_respiratory_infection    <str> '1', '0', '0', '1', '1', '1', '0', '1', '0', '0'
$ gerd                           <str> '0', '0', '0', 'NA', '0', '0', '0', '0', '0', '0'
$ rhinitis                       <str> '0', '1', '0', '0', '1', '0', 'NA', '0', '0', '1'
$ adherence                      <str> 'NA', 'NA', '0.7384196185', '0.0844686649', '0.5068119891', '0.0844686649', '0.1689373297', '0.2861035422', 'NA', '0.1689373297'
$ total_pre_index_charge         <str> '1224.7674731', '20290.534269', '2964.2541751', '3223.7088196', '1287.2543683', '5130.6846999', '627.90987742', '804.2881063', '354.4685639', '13403.327953'
$ pre_asthma_days                <str> '1', '0', 'NA', '0', '2', '0', '0', '0', '1', '1'
$ pre_asthma_charge              <str> '314', 'NA', '480', '0', '689', '0', '0', '0', '140.72', '175'
$ pre_asthma_pharma_charge       <str> '218.13', '44.98', '99.26', '59.58', 'NA', '21.41', '2.15', '59.79', '29.79', '45.59'
$ drug_s                         <str> '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'
$ female                         <str> 'NA', '0', '0', '1', '0', '0', '1', '1', '1', '0'
$ log_charges                    <str> '7.1105062871', '9.9179097641', '7.9943807368', '8.0782877831', '7.1602668324', '8.542994399', '6.4423966489', '6.6899575462', '5.8706196647', '9.5032583098'
$ log_asthma_charge              <str> '5.3850912153', '3.8062179465', '4.5977426702', 'NA', '3.3941727667', '3.0638581026', '0.7654678421', '4.0908384229', '3.3941727667', '3.8196883942'

In [6]:
binary_features = [
    "pneumonia","sinusitis","acute_bronchitis",
    "acute_laryngitis","upper_respiratory_infection",
    "gerd","rhinitis","drug_s","female"
]

numeric_features = [
    "index_age",
    "previous_asthma_drugs",
    "total_pre_index_cannisters_365",
    "pre_asthma_days",
]

skewed_numeric_features = [
    "total_pre_index_charge",
    "pre_asthma_charge",
    "pre_asthma_pharma_charge" ,
    "adherence"
]

In [7]:
def cast_float(df: pl.DataFrame) -> pl.DataFrame:
    return df.with_columns(
        pl.col(skewed_numeric_features)
        .replace("NA", None)
        .cast(pl.Float64, strict=False)
    )


def cast_int(df: pl.DataFrame) -> pl.DataFrame:
    return df.with_columns(
        pl.col(numeric_features)
        .replace("NA", None)
        .cast(pl.Int64, strict=False)
    )


def cast_binary(df: pl.DataFrame) -> pl.DataFrame:
    return df.with_columns(
        pl.col(binary_features)
        .replace("NA", None)
        .cast(pl.Int8, strict=False)
    )

In [8]:
# construct a data transformer from a user-defined function
# input columns → output columns (mêmes noms)
cast_int_transformer = FunctionTransformer(
    cast_int,
    feature_names_out="one-to-one"
)

cast_float_transformer = FunctionTransformer(
    cast_float,
    feature_names_out="one-to-one"
)

cast_binary_transformer = FunctionTransformer(
    cast_binary,
    feature_names_out="one-to-one"
)

log_transformer = FunctionTransformer(
    np.log1p,
    feature_names_out="one-to-one"
)

In [9]:
preprocessor = ColumnTransformer([

    # variables numériques classiques
    ("num_int", Pipeline([
        ("cast", cast_int_transformer),
        ("imputer", SimpleImputer(strategy="median"))
        #("scaler int ", StandardScaler())
    ]), numeric_features),

    # variables skewed (charges)
    ("skewed", Pipeline([
        ("cast", cast_float_transformer),
        ("imputer", SimpleImputer(strategy="median")),
        ("log", log_transformer),
        ("scaler int ", StandardScaler())
    ]), skewed_numeric_features),

    # variables binaires
    ("binary", Pipeline([
        ("cast", cast_binary_transformer),
        ("imputer", SimpleImputer(strategy="most_frequent"))
    ]), binary_features)

])

In [10]:
X= preprocessor.fit_transform(df)
feature_names = preprocessor.get_feature_names_out()

real = pl.DataFrame(X, schema=feature_names.tolist())

### Modele Avatar Article

Etape : 
1. comprendre la structure globale ("comment les patients sont organisés dans l’espace")
2. regarder localement : Pour chaque patient on regarde ses voisins les plus proches (patients qui lui ressemblent vraiment)
3. créer un nouvel individu : on fait un mélange pondéré de patients similaires (voisins) , elle depend : 
    - proximité : + un voisin est proche + il influence l avatar 
    - controle le hazard pour éviter de toujours générer la même chose
    - hiérarchie : certains voisins comptent plus que d’autres
    - On obtient un nouveau point situé dans la zone réaliste (interpolation)

In [11]:
def generate_synthetic_me(X,feature_names, k=10, n_components=10, noise=0.02, mix_ratio=0.2):

    # projection PCA
    pca = PCA(n_components=min(n_components, X.shape[1]))
    X_pca = pca.fit_transform(X)
    
    # KNN
    # on trouve les k voisins les plus proches dans l'espace PCA pour chaque point
    nbrs = NearestNeighbors(n_neighbors=k).fit(X_pca)
    _, indices = nbrs.kneighbors(X_pca)

    # global stats
    # on calcule la moyenne et la covariance de l'ensemble des données pour pouvoir faire du sampling global
    mean = np.mean(X, axis=0)
    cov = np.cov(X.T)
    cov += np.eye(cov.shape[0]) * 1e-3

    synthetic = []

    for i in range(len(X)):
        # on décide aléatoirement de faire du sampling global ou local pour chaque point, en fonction du mix_ratio
        if np.random.rand() < mix_ratio:
            # global sampling
            # on génère un point synthétique en échantillonnant à partir d'une distribution normale multivariée définie par la moyenne et la covariance de l'ensemble des données
            point = np.random.multivariate_normal(mean, cov)

        else:
            # local generation
            # on génère un point synthétique en interpolant entre deux voisins aléatoires parmi les k plus proches voisins du point i dans l'espace PCA
            neighbors = X_pca[indices[i]]
            # on choisit deux voisins aléatoires parmi les k plus proches voisins
            i1, i2 = np.random.choice(k, 2, replace=False) # indices des deux voisins choisis
            alpha = np.random.rand() # coefficient d'interpolation aléatoire entre 0 et 1
            point_pca = alpha * neighbors[i1] + (1 - alpha) * neighbors[i2] 
            # interpolation linéaire entre les deux voisins dans l'espace PCA pour créer un point synthétique qui est une combinaison des caractéristiques des deux voisins, ce qui permet de capturer la structure locale des données tout en introduisant de la variabilité.

            # FIX
            point = pca.inverse_transform(point_pca.reshape(1, -1))[0]
            # on ramène le point synthétique dans l'espace original des données en utilisant la transformation inverse de PCA, ce qui permet de conserver les caractéristiques originales des données tout en ayant généré un point synthétique basé sur les voisins dans l'espace PCA.

        # bruit léger
        std = np.std(X, axis=0) # on calcule l'écart-type de chaque variable dans les données originales pour pouvoir ajouter un bruit proportionnel à la variabilité de chaque variable
        point += np.random.normal(0, noise * std) # on ajoute un bruit gaussien à chaque variable du point synthétique, où l'amplitude du bruit est proportionnelle à l'écart-type de la variable dans les données originales, ce qui permet d'introduire de la variabilité supplémentaire tout en respectant la distribution des données originales.

        synthetic.append(point)

    synthetic = np.array(synthetic) # on convertit la liste de points synthétiques en un tableau numpy pour faciliter les opérations ultérieures et l'intégration avec d'autres outils de traitement de données.

    return pl.DataFrame(synthetic, schema=feature_names)

In [12]:
# Variance Threshold

selector = VarianceThreshold(threshold=0.0)  # supprime variance nulle
X= selector.fit_transform(X)

# On garde les noms des features restantes
mask = selector.get_support()
feature_names = feature_names[mask]

# reconstruire REAL propre
real = pl.DataFrame(X, schema=feature_names.tolist())

# génération du dataset synthétique
X_synth = generate_synthetic_me(X,feature_names.tolist(), k=10 , noise=0.02, mix_ratio=0.2)
synthetic_df = pl.DataFrame(X_synth, schema=feature_names.tolist())

In [13]:
print(X_synth.shape)
print(len(feature_names))

(14575, 16)
16

In [14]:
real.describe()

shape: (9, 17)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sta ┆ num ┆ num ┆ num ┆ ske ┆ ske ┆ ske ┆ ske ┆ bin ┆ bin ┆ bin ┆ bin ┆ bin ┆ bin ┆ bin ┆ bin ┆ bin │
│ tis ┆ _in ┆ _in ┆ _in ┆ wed ┆ wed ┆ wed ┆ wed ┆ ary ┆ ary ┆ ary ┆ ary ┆ ary ┆ ary ┆ ary ┆ ary ┆ ary │
│ tic ┆ t__ ┆ t__ ┆ t__ ┆ __t ┆ __p ┆ __p ┆ __a ┆ __p ┆ __s ┆ __a ┆ __a ┆ __u ┆ __g ┆ __r ┆ __d ┆ __f │
│ --- ┆ ind ┆ tot ┆ pre ┆ ota ┆ re_ ┆ re_ ┆ dhe ┆ neu ┆ inu ┆ cut ┆ cut ┆ ppe ┆ erd ┆ hin ┆ rug ┆ ema │
│ str ┆ ex_ ┆ al_ ┆ _as ┆ l_p ┆ ast ┆ ast ┆ ren ┆ mon ┆ sit ┆ e_b ┆ e_l ┆ r_r ┆ --- ┆ iti ┆ _s  ┆ le  │
│     ┆ age ┆ pre ┆ thm ┆ re_ ┆ hma ┆ hma ┆ ce  ┆ ia  ┆ is  ┆ ron ┆ ary ┆ esp ┆ f64 ┆ s   ┆ --- ┆ --- │
│     ┆ --- ┆ _in ┆ a_d ┆ ind ┆ _ch ┆ _ph ┆ --- ┆ --- ┆ --- ┆ chi ┆ ngi ┆ ira ┆     ┆ --- ┆ f64 ┆ f64 │
│     ┆ f64 ┆ dex ┆ ays ┆ ex_ ┆ arg ┆ arm ┆ f64 ┆ f64 ┆ f64 ┆ tis ┆ tis ┆ tor ┆     ┆ f64 ┆     ┆     │
│     ┆     ┆ _ca ┆ --- ┆ cha ┆ e   ┆ a_c ┆     ┆     ┆     ┆ --- ┆ --- ┆ y_i ┆     ┆     ┆     ┆     │
│     ┆     ┆ nni ┆ f64 ┆ rge ┆ --- ┆ har ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ nfe ┆     ┆     ┆     ┆     │
│     ┆     ┆ …   ┆     ┆ --- ┆ f64 ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     │
│     ┆     ┆ --- ┆     ┆ f64 ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     │
│     ┆     ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ cou ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 │
│ nt  ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. │
│     ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ nul ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ l_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ oun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ mea ┆ 38. ┆ 0.8 ┆ 1.3 ┆ -2. ┆ -1. ┆ -2. ┆ -9. ┆ 0.0 ┆ 0.2 ┆ 0.2 ┆ 0.0 ┆ 0.2 ┆ 0.0 ┆ 0.3 ┆ 0.1 ┆ 0.6 │
│ n   ┆ 599 ┆ 153 ┆ 855 ┆ 418 ┆ 072 ┆ 593 ┆ 750 ┆ 454 ┆ 869 ┆ 362 ┆ 154 ┆ 013 ┆ 924 ┆ 642 ┆ 473 ┆ 687 │
│     ┆ 177 ┆     ┆ 92  ┆ 0e- ┆ 5e- ┆ 5e- ┆ 2e- ┆ 89  ┆ 98  ┆ 26  ┆ 37  ┆ 04  ┆ 87  ┆ 54  ┆ 76  ┆ 48  │
│     ┆     ┆     ┆     ┆ 16  ┆ 16  ┆ 16  ┆ 19  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ std ┆ 14. ┆ 0.6 ┆ 2.3 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 0.2 ┆ 0.4 ┆ 0.4 ┆ 0.1 ┆ 0.4 ┆ 0.2 ┆ 0.4 ┆ 0.3 ┆ 0.4 │
│     ┆ 434 ┆ 890 ┆ 450 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 083 ┆ 523 ┆ 247 ┆ 232 ┆ 009 ┆ 897 ┆ 812 ┆ 544 ┆ 706 │
│     ┆ 932 ┆ 1   ┆ 03  ┆ 34  ┆ 34  ┆ 34  ┆ 34  ┆ 81  ┆ 76  ┆ 77  ┆ 89  ┆ 88  ┆ 22  ┆ 37  ┆ 92  ┆ 8   │
│ min ┆ 12. ┆ 0.0 ┆ 0.0 ┆ -4. ┆ -1. ┆ -2. ┆ -1. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│     ┆ 0   ┆     ┆     ┆ 813 ┆ 377 ┆ 262 ┆ 274 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 55  ┆ 605 ┆ 794 ┆ 165 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 25% ┆ 28. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -1. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│     ┆ 0   ┆     ┆     ┆ 500 ┆ 377 ┆ 707 ┆ 789 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 96  ┆ 605 ┆ 973 ┆ 016 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 50% ┆ 41. ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ 0.3 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 │
│     ┆ 0   ┆     ┆     ┆ 408 ┆ 563 ┆ 229 ┆ 308 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 13  ┆ 14  ┆ 218 ┆ 038 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 75% ┆ 49. ┆ 1.0 ┆ 2.0 ┆ 0.5 ┆ 0.7 ┆ 0.6 ┆ 0.3 ┆ 0.0 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.0 ┆ 1.0 │
│     ┆ 0   ┆     ┆     ┆ 796 ┆ 199 ┆ 933 ┆ 989 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 82  ┆ 16  ┆ 11  ┆ 13  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ max ┆ 65. ┆ 2.0 ┆ 71. ┆ 3.7 ┆ 2.6 ┆ 2.8 ┆ 3.1 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 │
│     ┆ 0   ┆     ┆ 0   ┆ 433 ┆ 282 ┆ 287 ┆ 358 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 37  ┆ 78  ┆ 51  ┆ 74  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [15]:
synthetic_df.describe()

shape: (9, 17)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sta ┆ num ┆ num ┆ num ┆ ske ┆ ske ┆ ske ┆ ske ┆ bin ┆ bin ┆ bin ┆ bin ┆ bin ┆ bin ┆ bin ┆ bin ┆ bin │
│ tis ┆ _in ┆ _in ┆ _in ┆ wed ┆ wed ┆ wed ┆ wed ┆ ary ┆ ary ┆ ary ┆ ary ┆ ary ┆ ary ┆ ary ┆ ary ┆ ary │
│ tic ┆ t__ ┆ t__ ┆ t__ ┆ __t ┆ __p ┆ __p ┆ __a ┆ __p ┆ __s ┆ __a ┆ __a ┆ __u ┆ __g ┆ __r ┆ __d ┆ __f │
│ --- ┆ ind ┆ tot ┆ pre ┆ ota ┆ re_ ┆ re_ ┆ dhe ┆ neu ┆ inu ┆ cut ┆ cut ┆ ppe ┆ erd ┆ hin ┆ rug ┆ ema │
│ str ┆ ex_ ┆ al_ ┆ _as ┆ l_p ┆ ast ┆ ast ┆ ren ┆ mon ┆ sit ┆ e_b ┆ e_l ┆ r_r ┆ --- ┆ iti ┆ _s  ┆ le  │
│     ┆ age ┆ pre ┆ thm ┆ re_ ┆ hma ┆ hma ┆ ce  ┆ ia  ┆ is  ┆ ron ┆ ary ┆ esp ┆ f64 ┆ s   ┆ --- ┆ --- │
│     ┆ --- ┆ _in ┆ a_d ┆ ind ┆ _ch ┆ _ph ┆ --- ┆ --- ┆ --- ┆ chi ┆ ngi ┆ ira ┆     ┆ --- ┆ f64 ┆ f64 │
│     ┆ f64 ┆ dex ┆ ays ┆ ex_ ┆ arg ┆ arm ┆ f64 ┆ f64 ┆ f64 ┆ tis ┆ tis ┆ tor ┆     ┆ f64 ┆     ┆     │
│     ┆     ┆ _ca ┆ --- ┆ cha ┆ e   ┆ a_c ┆     ┆     ┆     ┆ --- ┆ --- ┆ y_i ┆     ┆     ┆     ┆     │
│     ┆     ┆ nni ┆ f64 ┆ rge ┆ --- ┆ har ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ nfe ┆     ┆     ┆     ┆     │
│     ┆     ┆ …   ┆     ┆ --- ┆ f64 ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     │
│     ┆     ┆ --- ┆     ┆ f64 ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     │
│     ┆     ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ cou ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 ┆ 145 │
│ nt  ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. ┆ 75. │
│     ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ nul ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ l_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ oun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ mea ┆ 38. ┆ 0.8 ┆ 1.3 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.2 ┆ 0.2 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.3 ┆ 0.1 ┆ 0.7 │
│ n   ┆ 667 ┆ 195 ┆ 594 ┆ 009 ┆ 014 ┆ 022 ┆ 048 ┆ 445 ┆ 567 ┆ 205 ┆ 145 ┆ 933 ┆ 889 ┆ 443 ┆ 419 ┆ 009 │
│     ┆ 584 ┆ 66  ┆ 16  ┆ 489 ┆ 342 ┆ 799 ┆ 372 ┆ 93  ┆ 46  ┆ 7   ┆ 28  ┆ 67  ┆ 56  ┆ 4   ┆ 1   ┆ 56  │
│ std ┆ 14. ┆ 0.6 ┆ 2.3 ┆ 0.8 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.0 ┆ 0.3 ┆ 0.2 ┆ 0.0 ┆ 0.2 ┆ 0.1 ┆ 0.4 ┆ 0.1 ┆ 0.4 │
│     ┆ 410 ┆ 165 ┆ 047 ┆ 880 ┆ 782 ┆ 127 ┆ 363 ┆ 962 ┆ 407 ┆ 934 ┆ 570 ┆ 156 ┆ 446 ┆ 155 ┆ 898 ┆ 239 │
│     ┆ 318 ┆ 95  ┆ 22  ┆ 71  ┆ 58  ┆ 17  ┆ 55  ┆ 32  ┆ 48  ┆ 19  ┆ 01  ┆ 93  ┆ 56  ┆ 9   ┆ 44  ┆ 64  │
│ min ┆ -6. ┆ -1. ┆ -7. ┆ -4. ┆ -3. ┆ -3. ┆ -3. ┆ -0. ┆ -1. ┆ -1. ┆ -0. ┆ -1. ┆ -0. ┆ -1. ┆ -1. ┆ -0. │
│     ┆ 359 ┆ 943 ┆ 519 ┆ 854 ┆ 488 ┆ 878 ┆ 333 ┆ 581 ┆ 278 ┆ 202 ┆ 456 ┆ 297 ┆ 965 ┆ 260 ┆ 430 ┆ 866 │
│     ┆ 829 ┆ 959 ┆ 404 ┆ 273 ┆ 533 ┆ 63  ┆ 481 ┆ 189 ┆ 053 ┆ 28  ┆ 43  ┆ 04  ┆ 676 ┆ 174 ┆ 22  ┆ 518 │
│ 25% ┆ 28. ┆ 0.2 ┆ 0.0 ┆ -0. ┆ -1. ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.3 │
│     ┆ 644 ┆ 445 ┆ 413 ┆ 461 ┆ 348 ┆ 650 ┆ 735 ┆ 274 ┆ 023 ┆ 436 ┆ 068 ┆ 829 ┆ 380 ┆ 303 ┆ 526 ┆ 339 │
│     ┆ 484 ┆ 76  ┆ 64  ┆ 559 ┆ 337 ┆ 693 ┆ 226 ┆ 27  ┆ 581 ┆ 86  ┆ 52  ┆ 38  ┆ 65  ┆ 53  ┆ 14  ┆ 14  │
│ 50% ┆ 40. ┆ 0.9 ┆ 1.0 ┆ 0.0 ┆ 0.3 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.1 ┆ 0.1 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.2 ┆ 0.1 ┆ 0.9 │
│     ┆ 883 ┆ 848 ┆ 027 ┆ 342 ┆ 493 ┆ 225 ┆ 332 ┆ 439 ┆ 942 ┆ 763 ┆ 139 ┆ 713 ┆ 944 ┆ 107 ┆ 302 ┆ 691 │
│     ┆ 98  ┆ 37  ┆ 41  ┆ 53  ┆ 19  ┆ 356 ┆ 455 ┆ 45  ┆ 49  ┆ 55  ┆ 16  ┆ 15  ┆     ┆ 38  ┆ 88  ┆ 52  │
│ 75% ┆ 49. ┆ 1.0 ┆ 1.9 ┆ 0.5 ┆ 0.6 ┆ 0.6 ┆ 0.3 ┆ 0.0 ┆ 0.4 ┆ 0.4 ┆ 0.0 ┆ 0.2 ┆ 0.1 ┆ 0.7 ┆ 0.2 ┆ 1.0 │
│     ┆ 227 ┆ 242 ┆ 827 ┆ 085 ┆ 844 ┆ 010 ┆ 278 ┆ 620 ┆ 834 ┆ 113 ┆ 228 ┆ 947 ┆ 407 ┆ 072 ┆ 296 ┆ 025 │
│     ┆ 163 ┆ 94  ┆ 46  ┆ 55  ┆ 1   ┆ 23  ┆ 42  ┆ 64  ┆ 29  ┆ 61  ┆ 11  ┆ 16  ┆ 38  ┆ 66  ┆ 1   ┆ 91  │
│ max ┆ 97. ┆ 3.1 ┆ 49. ┆ 3.6 ┆ 3.8 ┆ 3.3 ┆ 3.5 ┆ 0.9 ┆ 1.7 ┆ 1.7 ┆ 0.4 ┆ 1.8 ┆ 1.1 ┆ 2.0 ┆ 1.5 ┆ 2.4 │
│     ┆ 876 ┆ 801 ┆ 617 ┆ 459 ┆ 976 ┆ 608 ┆ 359 ┆ 217 ┆ 774 ┆ 617 ┆ 438 ┆ 890 ┆ 653 ┆ 497 ┆ 670 ┆ 139 │
│     ┆ 635 ┆ 73  ┆ 817 ┆ 79  ┆ 27  ┆ 11  ┆     ┆ 4   ┆ 13  ┆ 08  ┆ 62  ┆ 55  ┆ 94  ┆ 9   ┆ 05  ┆ 68  │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

### Métrique 1 : Wasserstein

similarité des distributions ? 
Proche de 0 = Parfaits

In [16]:
def compute_wasserstein(real: pl.DataFrame, synth: pl.DataFrame):
    scores = []

    for col in real.columns:
        r = real[col].to_numpy()
        s = synth[col].to_numpy()

        if np.std(r) < 1e-6:  # éviter constantes
            continue

        scores.append(wasserstein_distance(r, s))

    return np.mean(scores)

### Métrique 2 : corrélation

structure des relations entre variables
Proche de 0 parfait

In [17]:
def compute_correlation_diff(real: pl.DataFrame, synth: pl.DataFrame):

    real_np = real.to_numpy()
    synth_np = synth.to_numpy()

    corr_real = np.corrcoef(real_np, rowvar=False)
    corr_synth = np.corrcoef(synth_np, rowvar=False)

    diff = np.abs(corr_real - corr_synth) # calculer la différence absolue entre les matrices de corrélation

    return diff.mean() # retourner la moyenne de la différence de corrélation comme mesure globale de la similarité entre les datasets

### Métrique 3 : distance au plus proche voisin

- Les données synthétiques sont il proches des vraies ?
- Privacy : réeidentification possible du patient ? 
- distance entre réel et synthétique (privacy)
- Plus élevé = données protégées (meilleur confidentialité)

In [18]:
def compute_dcr(real: pl.DataFrame, synth: pl.DataFrame):
    X_real = real.to_numpy()
    X_synth = synth.to_numpy()

    # calculer les distances entre chaque point synthétique et tous les points réels
    distances = pairwise_distances(X_synth, X_real)  
    return distances.min(axis=1).mean() 
# retourner la distance moyenne du plus proche voisin (DCR) comme mesure de la similarité entre les datasets

### Evaluation

In [19]:
def evaluate(real: pl.DataFrame, synth: pl.DataFrame):

    w = compute_wasserstein(real, synth) # distance de Wasserstein (distribution)
    corr = compute_correlation_diff(real, synth) # mesure de différence de corrélation (important pour ML)
    dcr = compute_dcr(real, synth) # distance au plus proche voisin dans le réel (privacy)

    return {
        "wasserstein": w,
        "corr_diff": corr,
        "dcr": dcr
    }

In [20]:
# évaluation globale
results = evaluate(real, synthetic_df)

In [21]:
results

{'wasserstein': np.float64(0.16735603122775627),
 'corr_diff': np.float64(0.04305310719349263),
 'dcr': np.float64(1.1125998259410115)}

### Grille de recherche

In [22]:
grid_results = []

param_grid = {
    "k": [5, 10, 15],
    "n_components": [8, 10, 15],
    "noise": [0.005, 0.01, 0.02],
    "mix_ratio": [0.0, 0.1, 0.2]
}

combinations = list(itertools.product(
    param_grid["k"],
    param_grid["n_components"],
    param_grid["noise"],
    param_grid["mix_ratio"]
))

for k, n_comp, noise, mix_ratio in combinations:

    X_synth = generate_synthetic_me(
        X,
        feature_names.tolist(),
        k=k,
        n_components=n_comp,
        noise=noise,
        mix_ratio=mix_ratio
    )

    synth = pl.DataFrame(X_synth, schema=feature_names.tolist())

    w = compute_wasserstein(real, synth)
    corr = compute_correlation_diff(real, synth)
    dcr = compute_dcr(real, synth)

    grid_results.append({
        "k": k,
        "n_components": n_comp,
        "noise": noise,
        "mix_ratio": mix_ratio,
        "wasserstein": w,
        "corr": corr,
        "dcr": dcr
    })

KeyboardInterrupt:

In [ ]:
results_me = pl.DataFrame(grid_results)
results_me.sort("dcr") 
# trier par DCR pour trouver les meilleurs paramètres en termes de privacy (DCR plus élevé = meilleur)

Lorsque k Augmente : elle réduit la préservation des informations statistiques, perte de relation entre les variables (structure) , mais meilleurs confidentialités . Comforme a ce qui à été demontrer dans l article

In [ ]:
# wasserstein et corr doivent être minimisés, dcr maximisé
results_df = results_me.with_columns(
    score = +pl.col("wasserstein") + pl.col("corr") - pl.col("dcr")
)
# créer une nouvelle colonne "score" qui combine les trois métriques en donnant plus de poids à DCR (privacy) 
# et en pénalisant les scores de Wasserstein et de corrélation (plus ils sont bas, mieux c'est)

best = results_df.sort("score", descending=True).head(1)
print(best)

Les résultats montrent que le modèle reproduit fidèlement les distributions des données (Wasserstein ≈ 0.096) ainsi que les relations entre variables (corr ≈ 0.047). De plus, la distance au plus proche voisin (DCR ≈ 0.628) indique un bon niveau de confidentialité. Ainsi, le modèle permet de générer des données synthétiques réalistes tout en préservant la confidentialité des données originales.

***Le modèle reproduit bien les données et leurs relations, tout en gardant une bonne distance avec les données réelles, donc il est à la fois réaliste et sécurisé.***

In [ ]:
d

In [ ]:
# génération du dataset synthétique
X_synth_confid = generate_synthetic_me(X, k=5,n_components=15, random_state=42)
synthetic_df = pl.DataFrame(X_synth_confid, schema=feature_names.tolist())

### Les données synthetisé ressemble t-il statistiquement au donnée reel ?

#### Analyse statistiques

In [ ]:
def compare_stats(real: pl.DataFrame, synth: pl.DataFrame):
    rows = []

    for col in real.columns:
        r_mean = real[col].mean()
        s_mean = synth[col].mean()

        r_std = real[col].std()
        s_std = synth[col].std()

        rows.append({
            "feature": col,

            "real_mean": r_mean,
            "synth_mean": s_mean,

            # 
            "mean_diff": abs(s_mean - r_mean),

            "real_std": r_std,
            "synth_std": s_std,
            "std_diff": abs(s_std - r_std),
        })

    return pl.DataFrame(rows)

comparison = compare_stats(real, synthetic_df)
display(comparison)

In [ ]:
display(
    comparison.select([
        pl.mean("mean_diff").alias("avg_mean_diff"),
        pl.mean("std_diff").alias("avg_std_diff")
    ])
)

Les statistiques descriptives montrent que les moyennes des variables sont très proches entre les données réelles et synthétiques (écart ≈ 3.6%), ce qui indique une bonne reproduction des distributions. L’écart-type présente une différence modérée (≈ 10.9%), suggérant une légère perte de variabilité dans les données synthétiques.

In [ ]:
cols = real.columns
n = len(cols)

# taille grille
n_cols = 4
n_rows = math.ceil(n / n_cols)

plt.figure(figsize=(20, 5 * n_rows))

for i, col in enumerate(cols):
    plt.subplot(n_rows, n_cols, i + 1)

    sns.kdeplot(real[col], label="real", fill=True)
    sns.kdeplot(synthetic_df[col], label="synthetic", fill=True)

    plt.title(col)
    plt.legend()

plt.tight_layout()
plt.show()

Les distributions des variables numériques sont globalement bien reproduites dans les données synthétiques. En revanche, les variables binaires présentent des différences importantes, indiquant que leur structure n’est pas correctement capturée par le modèle

In [ ]:
x = "num_int__index_age"
y = "skewed__total_pre_index_charge"

plt.scatter(real[x], real[y], alpha=0.3, label="real")
plt.scatter(synthetic_df[x], synthetic_df[y], alpha=0.3, label="synthetic")

plt.legend()
plt.title("Real vs Synthetic")
plt.show()

Le nuage de points montre que les données synthétiques suivent globalement la même distribution que les données réelles. Cependant, elles apparaissent légèrement plus concentrées, ce qui indique une réduction de la variabilité.

### Les données synthetisé conserve t-elles les corrélation ?

In [ ]:
# matrices de corrélation
# foncé = corrélation similaire, clair = corrélation différente
real_corr = np.corrcoef(real.to_numpy(), rowvar=False)
synth_corr = np.corrcoef(synthetic_df.to_numpy(), rowvar=False)
diff_corr = np.abs(real_corr - synth_corr)

plt.figure()
plt.imshow(diff_corr)
plt.title("Correlation Difference (|Real - Synthetic|)")
plt.colorbar()
plt.xticks(range(len(real.columns)), real.columns, rotation=90)
plt.yticks(range(len(real.columns)), real.columns)
plt.show()

La plus part des relations sont bien gardées , mais les relations entre certains variables (sinusitis, bronchitis , laryngitis , infections ) sont mal reproduites.

### Est ce que les donnée original se trouve dans les données synthétisé ? Privacy

In [ ]:
def exact_match(real, synth):
    real_set = set(map(tuple, real.to_numpy()))
    synth_set = set(map(tuple, synth.to_numpy()))

    matches = real_set.intersection(synth_set)

    return len(matches)

n_matches = exact_match(real, synthetic_df)
print("Exact matches:", n_matches)

Aucune duplication observé . Y a t il un risque de réidentification ?

In [ ]:
# distances synth vs real
dist = pairwise_distances(synthetic_df, real)

# distance minimale pour chaque point synthétique
min_dist = dist.min(axis=1)

print("Distance minimale moyenne :", np.mean(min_dist))
print("Distance minimale min :", np.min(min_dist))

La distances minimale montre que les observations synthétiques sont globalement éloignées des données réelles (distance minimale moyenne ≈ 0.63), donc risque de réidentification tres faible. la distance minimale observée (≈ 0.0035) révèle que certaines observations synthétiques sont très proches de données réelles, suggérant un risque local de similarité élevée.

### Conclusion

Le modèle reproduit bien les distributions (écart moyen ≈ 3.6%) et les relations entre variables (corr ≈ 0.047). Les données synthétiques sont globalement proches des données réelles tout en restant suffisamment éloignées (DCR ≈ 0.63), garantissant la confidentialité. Quelques similarités locales subsistent, mais le compromis entre réalisme et sécurité est globalement satisfaisant.

***Le modèle génère des données réalistes sans copier les données originales, avec un bon équilibre entre qualité et confidentialité***